### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by Submoon** [Submoon/MyMan#48]
**It would be a good idea to migrate the code to typescript, especially for #28** 
- Less confusing code and docs
- I need types

**See:**
- [TypeScript migration docs](https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html)
- [Official TypeScript types for Discord.js](https://github.com/discordjs/discord.js-typings)

**TODO:**
- [ ] Configure TypeScript locally
- [ ] Configure TypeScript on the server
- [ ] Convert files to TypeScript
- [ ] Create types as needed
- [ ] Reorganize the project ?

**Comment by Submoon** [comment]
[WIP in branch feature/typescript](https://github.com/Submoon/MyMan/tree/feature/typescript)
